### ISSUE TITLE
add fortran-tutorial as topic

### ISSUE THREAD

**Issue by Beliavsky** [urbanjost/M_intrinsics#3]
Could you add fortran-tutorial as topic? Although this repo is not strictly speaking a tutorial, I think it is a valuable reference for Fortran learners.

**Comment by urbanjost** [comment]
Certainly. Did you just mean in the github description (I added it there) or something else?  

Note ultimately I am hoping to supersede this with the fortran-lang.org descriptions, but for a significant period I expect both to exist.

**Comment by Beliavsky** [comment]
As you did it, thanks.

**Comment by urbanjost** [comment]
No prob. I appreciate you taking an interest; and any help is always welcome.
