### ISSUE TITLE
manpages as archive files

### ISSUE THREAD

**Issue by msz59** [urbanjost/M_intrinsics#5]
README.md contains "The man-pages are available as archive files:" followe by two URLs, one for manpages.zip and second for manpages.tgz. 
1. The URLs are cross-linked (zip -> tgz, tgz -> zip)
2. Both files, when downloaded by 'wget', appear to be some JSON format files, not any ZIP or TGZ archives. Only when the URL is clicked, it opens another page, on which clicking the "Raw" button downloads the proper archive. Was that supposed to be that complicated?

**Comment by urbanjost** [comment]
Not sure if something changed in github or if the project was publishing from root and was changed to publish from docs/ directory without catching that, but it links through github.io now which appears to correct that.
